# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "github-action" ]
  pull_request:
    branches: [ "github-action" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o main -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: ${{ github.workspace }}/main

    - name: Deploy to target
      shell: bash
      env:
        SSH_PKEY: ${{ secrets.SSH_KEY }}
        ANSIBLE_HOST_KEY_CHECKING: false
      run: |
        echo "$SSH_PKEY" > ~/.ssh/id_rsa_gh
        chmod 600 ~/.ssh/id_rsa_gh
        ansible-playbook -i ~/.ssh/id_rsa_gh inventory.ini playbook.yml
